package pojo;
// Generated Feb 2, 2020 6:12:39 PM by Hibernate Tools 4.3.1



/**
 * Answer generated by hbm2java
 */
public class Answer  implements java.io.Serializable {


     private Integer id;
     private int idQuestion;
     private int subQuestionNo;
     private String subQuestionText;
     private String correctAnswer;

    public Answer() {
    }

    public Answer(int idQuestion, int subQuestionNo, String subQuestionText, String correctAnswer) {
       this.idQuestion = idQuestion;
       this.subQuestionNo = subQuestionNo;
       this.subQuestionText = subQuestionText;
       this.correctAnswer = correctAnswer;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdQuestion() {
        return this.idQuestion;
    }
    
    public void setIdQuestion(int idQuestion) {
        this.idQuestion = idQuestion;
    }
    public int getSubQuestionNo() {
        return this.subQuestionNo;
    }
    
    public void setSubQuestionNo(int subQuestionNo) {
        this.subQuestionNo = subQuestionNo;
    }
    public String getSubQuestionText() {
        return this.subQuestionText;
    }
    
    public void setSubQuestionText(String subQuestionText) {
        this.subQuestionText = subQuestionText;
    }
    public String getCorrectAnswer() {
        return this.correctAnswer;
    }
    
    public void setCorrectAnswer(String correctAnswer) {
        this.correctAnswer = correctAnswer;
    }




}


