package pojo;
// Generated Feb 2, 2020 6:12:39 PM by Hibernate Tools 4.3.1



/**
 * Questionsints generated by hbm2java
 */
public class Questionsints  implements java.io.Serializable {


     private Integer id;
     private int questionId;
     private int tsId;

    public Questionsints() {
    }

    public Questionsints(int questionId, int tsId) {
       this.questionId = questionId;
       this.tsId = tsId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(int questionId) {
        this.questionId = questionId;
    }
    public int getTsId() {
        return this.tsId;
    }
    
    public void setTsId(int tsId) {
        this.tsId = tsId;
    }




}


