package pojo;
// Generated Feb 2, 2020 6:12:39 PM by Hibernate Tools 4.3.1



/**
 * Savestate generated by hbm2java
 */
public class Savestate  implements java.io.Serializable {


     private Integer id;
     private int idSurvey;
     private String userUsername;
     private int idQuestion;
     private int subQuestionNo;
     private String userAnswer;

    public Savestate() {
    }

    public Savestate(int idSurvey, String userUsername, int idQuestion, int subQuestionNo, String userAnswer) {
       this.idSurvey = idSurvey;
       this.userUsername = userUsername;
       this.idQuestion = idQuestion;
       this.subQuestionNo = subQuestionNo;
       this.userAnswer = userAnswer;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdSurvey() {
        return this.idSurvey;
    }
    
    public void setIdSurvey(int idSurvey) {
        this.idSurvey = idSurvey;
    }
    public String getUserUsername() {
        return this.userUsername;
    }
    
    public void setUserUsername(String userUsername) {
        this.userUsername = userUsername;
    }
    public int getIdQuestion() {
        return this.idQuestion;
    }
    
    public void setIdQuestion(int idQuestion) {
        this.idQuestion = idQuestion;
    }
    public int getSubQuestionNo() {
        return this.subQuestionNo;
    }
    
    public void setSubQuestionNo(int subQuestionNo) {
        this.subQuestionNo = subQuestionNo;
    }
    public String getUserAnswer() {
        return this.userAnswer;
    }
    
    public void setUserAnswer(String userAnswer) {
        this.userAnswer = userAnswer;
    }




}


