package pojo;
// Generated Feb 2, 2020 6:12:39 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ts generated by hbm2java
 */
public class Ts  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String basicInfo;
     private boolean testSurvey;
     private boolean isPersonalised;
     private Date dateTimeStart;
     private Date dateTimeEnd;
     private int durationPagesNo;
     private String creatorUsername;

    public Ts() {
    }

    public Ts(String name, String basicInfo, boolean testSurvey, boolean isPersonalised, Date dateTimeStart, Date dateTimeEnd, int durationPagesNo, String creatorUsername) {
       this.name = name;
       this.basicInfo = basicInfo;
       this.testSurvey = testSurvey;
       this.isPersonalised = isPersonalised;
       this.dateTimeStart = dateTimeStart;
       this.dateTimeEnd = dateTimeEnd;
       this.durationPagesNo = durationPagesNo;
       this.creatorUsername = creatorUsername;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getBasicInfo() {
        return this.basicInfo;
    }
    
    public void setBasicInfo(String basicInfo) {
        this.basicInfo = basicInfo;
    }
    public boolean isTestSurvey() {
        return this.testSurvey;
    }
    
    public void setTestSurvey(boolean testSurvey) {
        this.testSurvey = testSurvey;
    }
    public boolean isIsPersonalised() {
        return this.isPersonalised;
    }
    
    public void setIsPersonalised(boolean isPersonalised) {
        this.isPersonalised = isPersonalised;
    }
    public Date getDateTimeStart() {
        return this.dateTimeStart;
    }
    
    public void setDateTimeStart(Date dateTimeStart) {
        this.dateTimeStart = dateTimeStart;
    }
    public Date getDateTimeEnd() {
        return this.dateTimeEnd;
    }
    
    public void setDateTimeEnd(Date dateTimeEnd) {
        this.dateTimeEnd = dateTimeEnd;
    }
    public int getDurationPagesNo() {
        return this.durationPagesNo;
    }
    
    public void setDurationPagesNo(int durationPagesNo) {
        this.durationPagesNo = durationPagesNo;
    }
    public String getCreatorUsername() {
        return this.creatorUsername;
    }
    
    public void setCreatorUsername(String creatorUsername) {
        this.creatorUsername = creatorUsername;
    }




}


