package pojo;
// Generated Feb 2, 2020 6:12:39 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String username;
     private String name;
     private String surname;
     private String password;
     private Date birthday;
     private String birthplace;
     private String jmbg;
     private String phone;
     private String email;
     private byte[] photo;
     private int userType;
     private boolean userRegistered;

    public User() {
    }

	
    public User(String username, String name, String surname, String password, String birthplace, String jmbg, String phone, String email, byte[] photo, int userType, boolean userRegistered) {
        this.username = username;
        this.name = name;
        this.surname = surname;
        this.password = password;
        this.birthplace = birthplace;
        this.jmbg = jmbg;
        this.phone = phone;
        this.email = email;
        this.photo = photo;
        this.userType = userType;
        this.userRegistered = userRegistered;
    }
    public User(String username, String name, String surname, String password, Date birthday, String birthplace, String jmbg, String phone, String email, byte[] photo, int userType, boolean userRegistered) {
       this.username = username;
       this.name = name;
       this.surname = surname;
       this.password = password;
       this.birthday = birthday;
       this.birthplace = birthplace;
       this.jmbg = jmbg;
       this.phone = phone;
       this.email = email;
       this.photo = photo;
       this.userType = userType;
       this.userRegistered = userRegistered;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getBirthplace() {
        return this.birthplace;
    }
    
    public void setBirthplace(String birthplace) {
        this.birthplace = birthplace;
    }
    public String getJmbg() {
        return this.jmbg;
    }
    
    public void setJmbg(String jmbg) {
        this.jmbg = jmbg;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public byte[] getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
    public int getUserType() {
        return this.userType;
    }
    
    public void setUserType(int userType) {
        this.userType = userType;
    }
    public boolean isUserRegistered() {
        return this.userRegistered;
    }
    
    public void setUserRegistered(boolean userRegistered) {
        this.userRegistered = userRegistered;
    }




}


